---

version: "3.7"
services:
  mysql8:
    image: mysql:8
    container_name: mysql8
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    ports:
      - "3306:3306/tcp"

# vim:ft=docker:et:ts=2:sw=2:sts=2:

