---

version: "3.2"
services:
  mysql5:
    image: mysql:5
    container_name: mysql5
    volumes:
      - ./data/mysql/config:/etc/mysql/
      - ./data/mysql/data/:/var/lib/mysql
    ports:
      - "3306:3306/tcp"
  api:
    build: api/.
    container_name: api
    depends_on:
      - mysql5
    volumes:
      - ./api/app:/app
    links:
      - mysql5
    ports:
      - "3000:3000/tcp"

