---

version: "3.2"
services:
  mysql8:
    image: mysql:8
    container_name: mysql8
    volumes:
      - ./data/mysql/config:/etc/mysql/
      - ./data/mysql/data/:/var/lib/mysql
    ports:
      - "3306:3306/tcp"

# vim:ft=docker:et:ts=2:sw=2:sts=2:

